import fs from 'node:fs';
import path from 'node:path';
import * as cheerio from 'cheerio';
import { id, now, slug, parseJson } from './utils.js';
import { one, all, run, save, audit } from './db.js';
import { writeYaml, writeMd } from './workspace.js';
import { scoreMd } from './scoring.js';

export function requirements(text){ return String(text||'').split(/\r?\n/).map(l=>l.trim()).filter(Boolean).filter(l=>/require|qualification|experience|skill|must|responsibil|you will|we need|looking for|preferred|ability/i.test(l)).slice(0,20); }
export function parseJob(text, fb={}){ const lines=String(text||'').split(/\r?\n/).map(l=>l.trim()).filter(Boolean); const find=k=>lines.find(l=>new RegExp('^'+k+'\\s*:','i').test(l))?.replace(new RegExp('^'+k+'\\s*:\\s*','i'),''); const heading=lines.find(l=>/^#\s+/.test(l)); return {title:fb.title||find('title')||(heading?heading.replace(/^#\s+/,''):'Imported role'),company:fb.company||find('company')||'Unknown company',location:fb.location||find('location')||'',description:text}; }
export function ensureCompany(s,name){ const cid=slug(name||'unknown-company'), at=now(); run(s,'INSERT OR IGNORE INTO companies (id,name,created_at,updated_at) VALUES (?,?,?,?)',[cid,name||'Unknown company',at,at]); return one(s,'SELECT * FROM companies WHERE id=?',[cid]); }
function publicUrl(u){ return String(u || '').startsWith('jobos:text:') ? '' : (u || ''); }
export function syncJob(s,jid){ const job=one(s,'SELECT * FROM jobs WHERE id=?',[jid]); if(!job) return; const score=parseJson(job.score_json,null), app=one(s,'SELECT * FROM applications WHERE job_id=?',[jid]), tasks=all(s,'SELECT * FROM tasks WHERE job_id=? ORDER BY due_at IS NULL,due_at,created_at',[jid]); const dir=path.join(s.p.jobs,jid); writeYaml(path.join(dir,'job.yaml'),{id:job.id,profileId:job.profile_id,title:job.title,company:job.company,location:job.location,url:publicUrl(job.url),source:job.source,requirements:parseJson(job.requirements_json,[]),compensation:job.compensation,workModel:job.work_model,status:job.status,fitScore:job.fit_score,score,application:app?{id:app.id,status:app.status,notes:app.notes,confirmationUrl:app.confirmation_url,updatedAt:app.updated_at}:null,updatedAt:job.updated_at}); writeMd(path.join(dir,'description.md'),job.description); if(app) writeYaml(path.join(dir,'application.yaml'),{id:app.id,status:app.status,notes:app.notes,confirmationUrl:app.confirmation_url,updatedAt:app.updated_at}); if(tasks.length) writeYaml(path.join(dir,'tasks.yaml'),tasks.map(t=>({id:t.id,title:t.title,type:t.type,dueAt:t.due_at,priority:t.priority,status:t.status,createdBy:t.created_by}))); if(score) writeMd(path.join(dir,'score.md'),scoreMd(job,score)); }
export function importText(s,{profileId,filePath,source='text_file',url=''}){ if(!one(s,'SELECT id FROM profiles WHERE id=?',[profileId])) throw Error(`Unknown profile: ${profileId}`); const text=fs.readFileSync(filePath,'utf8'), parsed=parseJob(text), company=ensureCompany(s,parsed.company), at=now(), jid=id('job',url||`${profileId}:${parsed.title}:${parsed.company}:${text}`), dbUrl=url||`jobos:text:${jid}`; const ex=one(s,'SELECT * FROM jobs WHERE id=? OR (profile_id=? AND url=?)',[jid,profileId,dbUrl]); if(ex) return {job:ex,created:false}; run(s,'INSERT INTO jobs (id,profile_id,company_id,title,company,location,url,source,description,requirements_json,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)',[jid,profileId,company.id,parsed.title,parsed.company,parsed.location,dbUrl,source,text,JSON.stringify(requirements(text)),at,at]); audit(s,'job.imported','job',jid,{jobId:jid,profileId,source,url:publicUrl(dbUrl)}); syncJob(s,jid); save(s); return {job:one(s,'SELECT * FROM jobs WHERE id=?',[jid]),created:true}; }
export async function importUrl(s,{profileId,url}){ let text; try { const r=await fetch(url,{headers:{'user-agent':'JobOS local CLI (+human-initiated import)'}}); const html=await r.text(); const $=cheerio.load(html); $('script,style,noscript').remove(); const title=($('title').first().text()||$('h1').first().text()||'Imported URL role').replace(/\s+/g,' ').trim(); const body=$('body').text().replace(/\s+/g,' ').trim(); text=`Title: ${title}\nCompany: Unknown company\nSource URL: ${url}\n\n${body.slice(0,12000)}`; } catch(e) { text=`Title: Imported URL role\nCompany: Unknown company\nSource URL: ${url}\n\nURL import was recorded, but content fetch failed: ${e.message}\nManual enrichment required before scoring or tailoring.`; } const tmp=path.join(s.p.state,`${id('urlimport',url)}.txt`); fs.writeFileSync(tmp,text); return importText(s,{profileId,filePath:tmp,source:'url',url}); }
export function listJobs(s){ return all(s,'SELECT jobs.*, applications.status AS application_status FROM jobs LEFT JOIN applications ON applications.job_id=jobs.id ORDER BY jobs.created_at DESC'); }
