import fs from 'node:fs';
import path from 'node:path';
import { id, now, slug, tokenize, parseJson } from './utils.js';
import { one, all, run, save, audit } from './db.js';
import { writeYaml, writeMd } from './workspace.js';

export function defaultPrefs(name){ return {targetRoleFamilies:[name],industries:[],companyStages:[],locations:[],salary:{min:null,max:null,currency:'USD'},dealbreakers:[],skills:slug(name).split('-').filter(Boolean),missionKeywords:[],values:[],workModel:'',communicationStyle:'concise, warm, evidence-grounded',searchStrategy:'focused',automationPolicy:{externalApply:'human_approval_required',externalSend:'human_approval_required',autoApply:'disabled',autoSend:'disabled'}}; }
export function extractMetrics(line){ return [...String(line).matchAll(/(?:\$[\d,.]+|\d+(?:\.\d+)?%|\d+x|\b\d{2,}\b)/gi)].map(m=>m[0]); }
export function structuredProofs(profileId, text, source){ return String(text||'').split(/\r?\n/).map(l=>l.trim().replace(/^[-*•]\s*/, '')).filter(l=>l.length>=20).filter(l=>/\b(built|led|managed|created|designed|improved|launched|reduced|increased|owned|shipped|analyzed|implemented|taught|researched|coordinated|facilitated|developed)\b/i.test(l)).slice(0,24).map((line,idx)=>({id:id('proof',`${profileId}:${idx}:${line}`),summary:line,evidence:source,skills:[...new Set(tokenize(line).filter(t=>t.length>3).slice(0,10))],metrics:extractMetrics(line),metadata:{origin:'resume_import',claimType:'experience',requiresHumanVerification:false}})); }
export function syncProfile(s, pid){ const p=one(s,'SELECT * FROM profiles WHERE id=?',[pid]); if(!p) return; const proofs=all(s,'SELECT * FROM proof_points WHERE profile_id=? ORDER BY created_at',[pid]); writeYaml(path.join(s.p.profiles,`${pid}.yaml`),{id:p.id,name:p.name,preferences:parseJson(p.preferences_json,{}),proofPoints:proofs.map(x=>({id:x.id,summary:x.summary,evidence:x.evidence,skills:parseJson(x.skills_json,[]),metrics:parseJson(x.metrics_json,[]),source:x.source,metadata:parseJson(x.metadata_json,{})})),updatedAt:p.updated_at}); writeMd(path.join(s.p.proofs,`${pid}.md`), ['# Proof points for '+p.name,'',...proofs.map(x=>`- **${x.id}:** ${x.summary}${x.evidence ? ` _(evidence: ${x.evidence})_` : ''}${parseJson(x.metrics_json,[]).length ? ` Metrics: ${parseJson(x.metrics_json,[]).join(', ')}` : ''}`),''].join('\n')); }
export function createProfile(s,name,opts={}){ const pid=slug(name); const ex=one(s,'SELECT * FROM profiles WHERE id=?',[pid]); if(ex) return {profile:ex,created:false}; const at=now(), resume=opts.fromResume ? fs.readFileSync(opts.fromResume,'utf8') : '', prefs=opts.preferences ? JSON.parse(fs.readFileSync(opts.preferences,'utf8')) : defaultPrefs(name); run(s,'INSERT INTO profiles VALUES (?,?,?,?,?,?)',[pid,name,JSON.stringify(prefs),resume,at,at]); const proofs=structuredProofs(pid,resume,opts.fromResume||'profile import'); for(const pr of proofs) run(s,'INSERT OR IGNORE INTO proof_points (id,profile_id,summary,evidence,skills_json,metrics_json,source,metadata_json,created_at) VALUES (?,?,?,?,?,?,?,?,?)',[pr.id,pid,pr.summary,pr.evidence,JSON.stringify(pr.skills),JSON.stringify(pr.metrics),pr.metadata.origin,JSON.stringify(pr.metadata),at]); audit(s,'profile.created','profile',pid,{proofPointsImported:proofs.length}); syncProfile(s,pid); save(s); return {profile:one(s,'SELECT * FROM profiles WHERE id=?',[pid]),created:true}; }
export function addProof(s,pid,summary,evidence='',skills=[],metrics=[]){ if(!one(s,'SELECT id FROM profiles WHERE id=?',[pid])) throw Error(`Unknown profile: ${pid}`); const at=now(), proofId=id('proof',`${pid}:${summary}:${evidence}`); const meta={origin:'manual',claimType:'experience',requiresHumanVerification:false}; run(s,'INSERT OR IGNORE INTO proof_points (id,profile_id,summary,evidence,skills_json,metrics_json,source,metadata_json,created_at) VALUES (?,?,?,?,?,?,?,?,?)',[proofId,pid,summary,evidence,JSON.stringify(skills),JSON.stringify(metrics.length?metrics:extractMetrics(summary)),'manual',JSON.stringify(meta),at]); audit(s,'proof_point.added','proof_point',proofId,{profileId:pid}); syncProfile(s,pid); save(s); return one(s,'SELECT * FROM proof_points WHERE id=?',[proofId]); }
export function listProofs(s,pid){ return all(s,'SELECT * FROM proof_points WHERE profile_id=? ORDER BY created_at',[pid]).map(p=>({...p,skills:parseJson(p.skills_json,[]),metrics:parseJson(p.metrics_json,[]),metadata:parseJson(p.metadata_json,{})})); }
