import fs from 'node:fs';
import path from 'node:path';
import { one, all, run, save, audit } from './db.js';
import { id, now, parseJson, tokenize } from './utils.js';
import { writeMd } from './workspace.js';
import { requirements } from './jobs.js';
function relevant(job,proofs){ const jt=new Set(tokenize(`${job.title}\n${job.description}`)); return proofs.map(p=>{const skills=parseJson(p.skills_json,[]), metrics=parseJson(p.metrics_json,[]), rel=tokenize(`${p.summary} ${skills.join(' ')}`).filter(t=>jt.has(t)).length; return {...p,skills,metrics,relevance:rel};}).sort((a,b)=>b.relevance-a.relevance); }
function saveArtifact(s,{job,prof,type,title,file,content,evidence,warnings}){ const rel=path.join('jobs',job.id,'artifacts',file), abs=path.join(s.p.ws,rel), at=now(), aid=id('artifact',`${type}:${job.id}:${prof.id}:${at}`); writeMd(abs,content); run(s,'INSERT INTO artifacts VALUES (?,?,?,?,?,?,?,?,?,?,?)',[aid,job.id,prof.id,type,rel,title,content,JSON.stringify(evidence),JSON.stringify(warnings),'draft_needs_human_review',at]); audit(s,'artifact.created','artifact',aid,{jobId:job.id,profileId:prof.id,type,path:rel,approvalStatus:'draft_needs_human_review'}); save(s); return {id:aid,path:rel,approvalStatus:'draft_needs_human_review',warnings}; }
export function tailor(s,jid,pid,kind){ const job=one(s,'SELECT * FROM jobs WHERE id=?',[jid]); if(!job) throw Error(`Unknown job: ${jid}`); const prof=one(s,'SELECT * FROM profiles WHERE id=?',[pid]); if(!prof) throw Error(`Unknown profile: ${pid}`); const proofs=all(s,'SELECT * FROM proof_points WHERE profile_id=?',[pid]), chosen=relevant(job,proofs).filter(p=>p.relevance>0).slice(0,kind==='resume'?5:3), warnings=[]; if(!proofs.length) warnings.push('No proof points exist for this profile; draft intentionally avoids unsupported achievement claims.'); else if(!chosen.length) warnings.push('No proof points matched job language; add evidence before strengthening this artifact.'); const evidence=chosen.map(p=>({proofPointId:p.id,summary:p.summary,evidence:p.evidence,skills:p.skills,metrics:p.metrics})); const warningBlock=warnings.length?warnings.map(w=>`- ${w}`).join('\n'):'- None from deterministic evidence checks.'; if(kind==='resume'){ const bullets=chosen.length?chosen.map(p=>`- ${p.summary}${p.evidence?` _(evidence: ${p.evidence})_`:''}${p.metrics?.length?` Metrics: ${p.metrics.join(', ')}`:''}`).join('\n'):'- Add evidence-backed accomplishments before using this resume externally.'; const reqBlock=requirements(job.description).length?requirements(job.description).map(r=>`- ${r}`).join('\n'):'- No explicit requirements extracted from the job text.'; const content=`# Tailored resume draft — ${prof.name} for ${job.title}\n\n**Company:** ${job.company}\n\n**Approval status:** Draft; human review required before submission.\n\n## Target role summary\nUse this foundation draft as a source-grounded outline. It includes only stored proof points; it does not invent metrics, employers, credentials, or claims. Sprint 2 will replace this deterministic draft with LLM tailoring.\n\n## Evidence-backed highlights\n${bullets}\n\n## Job requirements to address\n${reqBlock}\n\n## Evidence warnings\n${warningBlock}\n\n## Human review checklist\n- Confirm every claim is true and current.\n- Add missing proof points for important requirements before exporting a final resume.\n- Do not submit from JobOS; external applications remain human-gated.\n`; return saveArtifact(s,{job,prof,type:'resume',title:`Tailored resume for ${job.title}`,file:'resume-tailored.md',content,evidence,warnings}); }
 const proofParagraph=chosen.length?chosen.map(p=>`- ${p.summary}${p.evidence?` (evidence: ${p.evidence})`:''}`).join('\n'):'- [Add a verified proof point before sending.]'; const content=`# Cover letter draft — ${job.title} at ${job.company}\n\n**Approval status:** Draft; human review required before sending.\n\nDear hiring team,\n\nI am interested in ${job.title} at ${job.company}. The role appears aligned with my ${prof.name} search profile.\n\nEvidence I can safely claim from my proof library:\n${proofParagraph}\n\nI would tailor the final version after confirming the job requirements, company context, and any sensitive screening questions manually.\n\n## Evidence warnings\n${warningBlock}\n\n## External-action gate\nJobOS generated this draft only. It did not send email, submit forms, or contact anyone.\n`; return saveArtifact(s,{job,prof,type:'cover_letter',title:`Cover letter for ${job.title}`,file:'cover-letter.md',content,evidence,warnings}); }
