import fs from 'node:fs';
import path from 'node:path';
import http from 'node:http';
import { esc } from './utils.js';
import { state } from './analytics.js';
import { handleApi } from './api.js';

const stages = ['saved','researching','materials-ready','applied','recruiter-screen','interview','offer','rejected','withdrawn','ghosted'];

function option(value, label = value) { return `<option value="${esc(value)}">${esc(label)}</option>`; }

function html(st) {
  const profileOptions = st.profiles.map(p => option(p.id, `${p.name} (${p.id})`)).join('');
  const jobOptions = st.jobs.map(j => option(j.id, `${j.title} — ${j.company}`)).join('');
  const stakeholderOptions = (st.stakeholders || []).map(s => option(s.id, `${s.name} — ${s.role || 'stakeholder'}`)).join('');
  const outreachArtifactOptions = st.artifacts.filter(a => a.type === 'outreach').map(a => option(a.id, `${a.title} (${a.id})`)).join('');
  const outreachThreadOptions = (st.outreachThreads || []).map(t => option(t.id, `${t.id} — ${t.status}`)).join('');
  const kanban = stages.map(stage => {
    const apps = st.applications.filter(a => a.status === stage);
    const cards = apps.map(a => `<article class="card"><strong>${esc(a.title)}</strong><br><span>${esc(a.company)}</span><br><code>${esc(a.id)}</code><form data-api="/api/applications/${esc(a.id)}" data-method="PATCH"><select name="status">${stages.map(s => `<option value="${s}" ${s === a.status ? 'selected' : ''}>${s}</option>`).join('')}</select><input name="notes" placeholder="status note"><button>Update</button></form></article>`).join('') || '<p class="muted">No cards</p>';
    return `<section class="lane"><h3>${esc(stage)} <span>${apps.length}</span></h3>${cards}</section>`;
  }).join('');
  const jobs = st.jobs.map(x => `<tr><td><strong>${esc(x.title)}</strong><br><span class="muted">${esc(x.id)}</span></td><td>${esc(x.company)}</td><td>${esc(x.fit_score ?? '—')}${x.high_fit ? ' · high fit' : ''}</td><td>${esc(x.status || 'imported')} / ${esc(x.application_status || 'not tracked')}</td><td><form data-api="/api/jobs/${esc(x.id)}" data-method="PATCH"><input name="title" value="${esc(x.title)}"><input name="company" value="${esc(x.company)}"><button>Save</button></form></td></tr>`).join('') || '<tr><td colspan="5" class="muted">No jobs imported.</td></tr>';
  const discoveryRuns = (st.discoveryRuns || []).slice(0, 8).map(r => `<li><code>${esc(r.createdAt)}</code> ${esc(r.outputs?.searchName || r.inputs?.searchName || r.id)} — ${esc(r.status)} — fetched ${esc(r.outputs?.counts?.fetched ?? 0)}, imported ${esc(r.outputs?.counts?.imported ?? 0)}, high fit ${esc(r.outputs?.counts?.highFit ?? 0)}</li>`).join('') || '<li class="muted">No discovery runs yet.</li>';
  const reviewQueue = (st.reviewQueue || []).map(j => `<article class="card"><strong>${esc(j.title)}</strong><br><span>${esc(j.company)} · ${esc(j.location || 'location not specified')} · ${esc(j.fit_score ?? 'unscored')}/100${j.high_fit ? ' · high fit' : ''}</span><br><a href="${esc(j.url)}">${esc(j.url || 'No public URL')}</a><form data-api="/api/jobs/${esc(j.id)}" data-method="PATCH"><button name="status" value="saved">Accept</button><button name="status" value="archived">Archive</button></form></article>`).join('') || '<p class="muted">No jobs waiting for review.</p>';
  const artifacts = st.artifacts.map(a => `<article class="card"><strong>${esc(a.title)}</strong><br><code>${esc(a.id)}</code><p>${esc(a.type)} · ${esc(a.approval_status)}</p><a href="/workspace/${esc(a.path)}">Open draft</a><form data-api="/api/artifacts/${esc(a.id)}" data-method="PATCH"><button name="approvalStatus" value="approved">Approve</button><button name="approvalStatus" value="rejected">Reject</button><button name="approvalStatus" value="draft_needs_human_review">Back to draft</button></form></article>`).join('') || '<p class="muted">No artifacts yet.</p>';
  const contactRows = (st.contactPoints || []).map(c => `<tr><td><strong>${esc(c.value)}</strong><br><code>${esc(c.id)}</code></td><td>${esc(c.type)}</td><td>${esc(c.evidenceTier)} / ${esc(c.verificationStatus)}</td><td>${esc(c.confidence)}</td><td>${c.humanApproved ? 'approved' : 'needs review'}${c.doNotUse ? ' · suppressed' : ''}</td><td><form data-api="/api/research/contacts/${esc(c.id)}/approve" data-method="POST"><button>Approve</button></form><form data-api="/api/research/contacts/${esc(c.id)}/suppress" data-method="POST"><input name="reason" placeholder="reason"><button>Suppress</button></form></td></tr>`).join('') || '<tr><td colspan="6" class="muted">No contact points discovered.</td></tr>';
  const candidateRows = (st.personCandidates || []).slice(0, 12).map(c => `<li><strong>${esc(c.name)}</strong> — ${esc(c.role || 'role unknown')} <span class="muted">${esc(c.confidence)} · ${esc(c.status)}</span></li>`).join('') || '<li class="muted">No person candidates staged.</li>';
  const patternRows = (st.emailPatterns || []).slice(0, 12).map(p => `<li><code>${esc(p.domain)} ${esc(p.pattern)}</code> <span class="muted">${esc(p.support_count)} example(s) · ${esc(p.confidence)}</span></li>`).join('') || '<li class="muted">No email patterns inferred.</li>';
  const planRows = (st.outreachPlans || []).slice(0, 8).map(p => `<tr><td><code>${esc(p.id)}</code></td><td>${esc(p.channel)}</td><td>${esc(p.path_strength)}</td><td>${esc((p.warnings || []).join('; '))}</td></tr>`).join('') || '<tr><td colspan="4" class="muted">No outreach plans yet.</td></tr>';
  const tasks = st.tasks.map(t => `<li>${esc(t.title)} — ${esc(t.priority)} — ${esc(t.due_at || 'no due date')}</li>`).join('') || '<li class="muted">No open tasks.</li>';
  const profiles = st.profiles.map(p => `<article class="card"><h3>${esc(p.name)}</h3><p><code>${esc(p.id)}</code></p></article>`).join('') || '<p class="muted">No profiles yet.</p>';
  const automationRows = (st.automations || []).map(a => `<tr><td><strong>${esc(a.name)}</strong><br><span class="muted">${esc(a.actionId)}</span></td><td><code>${esc(a.schedule)}</code></td><td>${esc(a.profileId || 'all')}</td><td>${a.enabled ? 'enabled' : 'disabled'}</td><td>${esc(a.nextDueAt || '—')}</td><td>${esc(a.lastStatus || 'never_run')}</td><td><form data-api="/api/automations/${esc(a.id)}" data-method="PATCH"><button name="enabled" value="${a.enabled ? 'false' : 'true'}">${a.enabled ? 'Disable' : 'Enable'}</button></form><form data-api="/api/automations/${esc(a.id)}/run" data-method="POST"><button>Run</button></form></td></tr>`).join('') || '<tr><td colspan="7" class="muted">No automations configured.</td></tr>';
  const runRows = (st.automationRuns || []).slice(0, 8).map(r => `<tr><td><code>${esc(r.createdAt)}</code></td><td>${esc(r.automationName || r.trigger)}</td><td>${esc(r.status)}</td><td>${esc(r.durationMs || 0)}ms</td><td>${esc(r.error || '')}</td></tr>`).join('') || '<tr><td colspan="5" class="muted">No runs yet.</td></tr>';
  const scheduledArtifactIds = new Set((st.automationRuns || []).flatMap(r => Array.isArray(r.outputs?.followups) ? r.outputs.followups.map(f => f.artifactId).filter(Boolean) : []));
  const scheduledDrafts = st.artifacts.filter(a => a.approval_status === 'draft_needs_human_review' && scheduledArtifactIds.has(a.id)).map(a => `<li><a href="/workspace/${esc(a.path)}">${esc(a.title)}</a> <span class="muted">${esc(a.type)} · ${esc(a.created_at)}</span></li>`).join('') || '<li class="muted">No scheduled draft artifacts awaiting review.</li>';
  const outreachDue = (st.outreachDue || []).map(item => `<li><strong>${esc(item.title)}</strong> <span class="muted">due ${esc(item.dueAt || 'now')} · ${esc(item.stakeholderName || 'stakeholder')} · ${esc(item.company || '')}</span></li>`).join('') || '<li class="muted">No due outreach follow-ups.</li>';
  const outreachThreads = (st.outreachThreads || []).map(t => `<tr><td><code>${esc(t.id)}</code><br><span class="muted">${esc(t.goal)}</span></td><td>${esc(t.status)}</td><td>${esc(t.channel || '')}</td><td>${esc(t.sentAt || '')}</td><td>${esc(t.nextFollowupAt || '')}</td></tr>`).join('') || '<tr><td colspan="5" class="muted">No outreach threads yet.</td></tr>';
  const audit = st.audit.map(a => `<li><code>${esc(a.created_at)}</code> ${esc(a.action)} ${esc(a.entity_type)}:${esc(a.entity_id)} (${esc(a.external_side_effect)})</li>`).join('') || '<li class="muted">No audit events yet.</li>';
  return `<!doctype html><html><head><meta charset="utf-8"><title>JobOS Local Dashboard</title><style>
body{font-family:Inter,system-ui;margin:0;background:#0f172a;color:#e2e8f0}.app{display:grid;grid-template-columns:230px 1fr;min-height:100vh}.rail{background:#020617;padding:18px;position:sticky;top:0;height:100vh}.rail a{display:block;color:#cbd5e1;padding:8px;text-decoration:none}main{padding:24px}section.panel{background:#111827;border:1px solid #334155;border-radius:16px;padding:18px;margin:14px 0}.card{background:#0b1220;border:1px solid #1f2937;padding:12px;border-radius:10px;margin:8px 0}.muted{color:#94a3b8}table{width:100%;border-collapse:collapse}td,th{border-bottom:1px solid #334155;padding:8px;text-align:left}.banner{background:#422006}.kanban{display:grid;grid-template-columns:repeat(5,minmax(190px,1fr));gap:10px;overflow-x:auto}.lane{background:#0b1220;border:1px solid #334155;border-radius:12px;padding:10px;min-width:190px}input,select,textarea,button{margin:4px;padding:8px;border-radius:8px;border:1px solid #475569}button{background:#38bdf8;color:#082f49;font-weight:700;cursor:pointer}form.grid{display:grid;grid-template-columns:repeat(2,minmax(180px,1fr));gap:8px}textarea{min-height:110px;grid-column:1/-1}.status{position:fixed;right:18px;bottom:18px;background:#022c22;border:1px solid #059669;border-radius:10px;padding:10px;display:none}</style></head><body><div class="app"><nav class="rail"><h2>JobOS</h2><a href="#today">Today</a><a href="#discovery">Discovery</a><a href="#board">Kanban board</a><a href="#jobs">Jobs</a><a href="#applications">Applications</a><a href="#artifacts">Artifact review</a><a href="#research">Research</a><a href="#contacts">Contacts</a><a href="#outreach">Outreach</a><a href="#tasks">Tasks</a><a href="#profile-proof">Profile & Proof</a><a href="#automations">Automations</a><a href="#audit">Audit Log</a></nav><main><section class="panel banner"><strong>Human gate:</strong> JobOS cannot submit applications, send outreach, or touch external accounts. This dashboard only edits local JobOS state and reviews drafts.</section>
<section id="today" class="panel"><h1>Today / Priority Brief</h1><p>Interactive local dashboard: create jobs/applications/proof points, move the kanban board, and approve/reject draft artifacts. Agents should still prefer CLI/API/MCP for repeatable operations.</p></section>
<section id="discovery" class="panel"><h2>Discovery</h2><h3>Review queue</h3>${reviewQueue}<h3>Recent runs</h3><ul>${discoveryRuns}</ul></section>
<section id="board" class="panel"><h2>Kanban-style application status board</h2><div class="kanban">${kanban}</div></section>
<section id="jobs" class="panel"><h2>Jobs</h2><form class="grid" data-api="/api/jobs" data-method="POST"><select name="profileId" required>${profileOptions}</select><input name="title" placeholder="Title" required><input name="company" placeholder="Company" required><input name="location" placeholder="Location"><input name="url" placeholder="URL"><textarea name="description" placeholder="Paste job description"></textarea><button>Create job</button></form><table><thead><tr><th>Role</th><th>Company</th><th>Fit</th><th>Status</th><th>Edit</th></tr></thead><tbody>${jobs}</tbody></table></section>
<section id="applications" class="panel"><h2>Applications</h2><form data-api="/api/applications" data-method="POST"><select name="jobId" required>${jobOptions}</select><select name="status">${stages.map(s => option(s)).join('')}</select><input name="notes" placeholder="Internal note"><button>Create application</button></form></section>
<section id="artifacts" class="panel"><h2>Artifact review UI</h2><p class="muted">Approve/reject only local draft artifacts; external submission remains manual.</p>${artifacts}</section>
<section id="research" class="panel"><h2>Research</h2><p>Use CLI/API/MCP to generate dossiers and stakeholder briefs, then inspect files from each job workspace.</p></section>
<section id="contacts" class="panel"><h2>Contact research</h2><p class="muted">Contacts are local review records. Approval does not send anything.</p><form data-api="/api/research/contacts/discover" data-method="POST"><select name="jobId" required>${jobOptions}</select><button>Discover contacts</button></form><table><thead><tr><th>Contact</th><th>Type</th><th>Tier / verification</th><th>Confidence</th><th>Review</th><th>Action</th></tr></thead><tbody>${contactRows}</tbody></table><h3>Email patterns</h3><ul>${patternRows}</ul><h3>Person candidates</h3><ul>${candidateRows}</ul></section>
<section id="outreach" class="panel"><h2>Outreach</h2><p>Draft-only outreach is stored as artifacts/tasks. JobOS never sends messages.</p><form data-api="/api/outreach/plan" data-method="POST"><select name="jobId" required>${jobOptions}</select><select name="profileId" required>${profileOptions}</select><select name="stakeholderId">${option('', 'Any stakeholder')}${stakeholderOptions}</select><select name="goal"><option>informational</option><option>referral</option></select><button>Plan path</button></form><h3>Plans</h3><table><thead><tr><th>Plan</th><th>Channel</th><th>Strength</th><th>Warnings</th></tr></thead><tbody>${planRows}</tbody></table><form data-api="/api/outreach/draft" data-method="POST"><select name="jobId" required>${jobOptions}</select><select name="profileId" required>${profileOptions}</select><select name="stakeholderId" required>${stakeholderOptions}</select><select name="goal"><option>informational</option><option>referral</option></select><button>Draft outreach</button></form><form data-api="/api/outreach/mark-sent" data-method="POST"><select name="artifactId" required>${outreachArtifactOptions}</select><select name="channel"><option>email</option><option>linkedin</option><option>other</option></select><input name="notes" placeholder="Human-sent note"><button>Record sent</button></form><form data-api="/api/outreach/schedule-followup" data-method="POST"><select name="threadId" required>${outreachThreadOptions}</select><input name="afterDays" type="number" min="0" value="7"><button>Schedule follow-up</button></form><h3>Due follow-ups</h3><ul>${outreachDue}</ul><h3>Threads</h3><table><thead><tr><th>Thread</th><th>Status</th><th>Channel</th><th>Sent</th><th>Next follow-up</th></tr></thead><tbody>${outreachThreads}</tbody></table></section>
<section id="tasks" class="panel"><h2>Tasks</h2><form data-api="/api/tasks" data-method="POST"><input name="title" placeholder="Task title" required><select name="priority"><option>normal</option><option>high</option><option>low</option></select><button>Create task</button></form><ul>${tasks}</ul></section>
<section id="profile-proof" class="panel"><h2>Profile & Proof</h2>${profiles}<form data-api="/api/proofs" data-method="POST"><select name="profileId" required>${profileOptions}</select><input name="summary" placeholder="Evidence-backed proof point" required><input name="evidence" placeholder="Evidence/source"><input name="skills" placeholder="comma-separated skills"><button>Add proof point</button></form></section>
<section id="automations" class="panel"><h2>Automations</h2><p>Automation runs are internal-only and audited. No external side effects without human approval.</p><table><thead><tr><th>Name</th><th>Schedule</th><th>Profile</th><th>State</th><th>Next due</th><th>Last</th><th>Actions</th></tr></thead><tbody>${automationRows}</tbody></table><h3>Recent runs</h3><table><thead><tr><th>Started</th><th>Automation</th><th>Status</th><th>Duration</th><th>Error</th></tr></thead><tbody>${runRows}</tbody></table><h3>Drafts awaiting review</h3><ul>${scheduledDrafts}</ul></section>
<section id="audit" class="panel"><h2>Audit Log</h2><ul>${audit}</ul></section></main></div><div id="status" class="status"></div><script>
const statusBox=document.getElementById('status');
function payload(form, submitter){ const data={}; for (const el of form.elements) { if(!el.name || el.type==='submit' || el.tagName==='BUTTON') continue; const v=el.value; if(v!=='' || el.required) data[el.name]=el.name==='skills'?v.split(',').map(x=>x.trim()).filter(Boolean):v; } if(submitter?.name) data[submitter.name]=submitter.value; return data; }
for (const form of document.querySelectorAll('form[data-api]')) form.addEventListener('submit', async ev => { ev.preventDefault(); const submitter=ev.submitter; const res=await fetch(form.dataset.api,{method:form.dataset.method||'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload(form, submitter))}); const text=await res.text(); statusBox.style.display='block'; statusBox.textContent=res.ok?'Saved local JobOS state':'Error: '+text; if(res.ok) setTimeout(()=>location.reload(),500); });
</script></body></html>`;
}

export function web(s, { port = 4317, host = '127.0.0.1', onReady = null } = {}) {
  const server = http.createServer(async (req, res) => {
    const raw = req.url || '/';
    if (raw.startsWith('/workspace/') && /(\.\.|%2e%2e)/i.test(raw)) { res.writeHead(400); res.end('Bad workspace path'); return; }
    const u = new URL(raw, `http://${req.headers.host}`);
    const api = await handleApi(s, req, res, u); if (api !== false) return;
    if (u.pathname.startsWith('/workspace/')) {
      const rel = u.pathname.replace(/^\/workspace\//, ''), abs = path.resolve(s.p.ws, rel);
      const wsRoot = path.resolve(s.p.ws);
      if (!(abs === wsRoot || abs.startsWith(wsRoot + path.sep)) || !fs.existsSync(abs) || fs.statSync(abs).isDirectory()) { res.writeHead(404); res.end('Not found'); return; }
      res.writeHead(200, { 'content-type': 'text/plain; charset=utf-8' }); res.end(fs.readFileSync(abs)); return;
    }
    if (u.pathname !== '/') { res.writeHead(404); res.end('Not found'); return; }
    res.writeHead(200, { 'content-type': 'text/html; charset=utf-8' }); res.end(html(state(s)));
  });
  server.listen(port, host, () => onReady?.()); return server;
}
